# Regenerate wizard task suggestions as complete sentences (js/app.js).
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
path = ROOT / "js" / "app.js"
s = path.read_text(encoding="utf-8")
start = s.index("const WIZ_DEFAULT_COMMON_TASKS=")
end = s.index("\n};", s.index("const WIZ_COMMON_TASKS_BY_CATEGORY=")) + len("\n};")


def q(t):
    return "'" + t.replace("\\", "\\\\").replace("'", "\\'") + "'"


def js_arr(lines):
    return "[\n  " + ",\n  ".join(q(x) for x in lines) + "\n]"


DEFAULT = [
    "Block ninety minutes on the one task that is actually due this week before you distract yourself.",
    "Email your manager a short status update before four p.m. so nobody has to chase you.",
    "Book a dentist cleaning in the next thirty days and put it on the calendar before you forget.",
    "Pay two overdue household bills online tonight and save the confirmation PDFs in one folder.",
    "Walk eight thousand steps after lunch and jot one line about how your knees felt afterward.",
    "Declutter the junk drawer and donate anything you have not touched in twelve whole months.",
    "Call a sibling for twenty minutes with no agenda besides catching up like you mean it.",
    "Back up laptop photos to an external drive before bed so you sleep without dread tonight.",
    "Review next week's calendar and cancel one low-value meeting before Monday morning arrives.",
    "Write three concrete Monday goals on a sticky note and place it where your eyes land first.",
]

# Each category: 10 complete sentences, ~10-22 words, natural voice.
CATS = {
    "work": [
        "Clear your inbox under twenty threads before lunch today, then archive newsletters you never read.",
        "Write a tight half-page on yesterday's customer bug and post it in the team channel by three p.m.",
        "Book a twenty-five-minute one-on-one to unblock the dashboard redesign before Friday afternoon.",
        "Update the roadmap deck with shipped items this sprint and email the link to every stakeholder.",
        "Record a three-minute Loom on the new feature flag so support can answer tickets without paging you.",
        "Block two hours of deep work with Slack on Do Not Disturb until the spec reviewers asked for is finished.",
        "Reply to vendor contract redlines with bullet decisions so legal can move before Tuesday end of day.",
        "Groom the backlog by closing stale tickets, re-estimating three epics, and assigning owners for next sprint.",
        "Draft five honest standup bullets on launch risks so the room stays grounded tomorrow morning.",
        "Export last month's time-tracking CSV and attach it to the finance email they keep asking about.",
    ],
    "life": [
        "Do laundry Thursday night before your brother gets back so the guest room actually feels welcoming.",
        "Pay the car registration online tonight so you are not fined when the grace period quietly ends.",
        "Schedule a haircut for Saturday morning because your calendar is empty after ten a.m.",
        "Renew your driver's license this week if it expires before the summer road trips you promised.",
        "Call the dentist and book a cleaning in the next thirty days before the good slots vanish.",
        "Spend twenty minutes sorting mail and shred anything that still shows your old apartment address.",
        "Update your emergency contact list and text it to the friend who watches your kid sometimes.",
        "Pack the donation bag for Saturday pickup so the closet finally stops feeling like a junkyard.",
        "Review subscriptions tonight and cancel the two apps you have not opened since January first.",
        "Write Sunday's meal plan on paper and tape it to the fridge so the week starts with less chaos.",
    ],
    "health": [
        "Walk thirty brisk minutes after dinner and note whether your knee felt better than yesterday night.",
        "Book a physical with your primary care doctor before your insurance deductible resets next month.",
        "Refill daily medications at the pharmacy you trust and set a loud reminder for weekday mornings.",
        "Stretch hips and hamstrings for twelve minutes after desk work so your lower back stops yelling.",
        "Schedule a therapy intake if you have been postponing it since New Year's resolutions felt urgent.",
        "Drink two liters of water today and skip afternoon coffee if you slept badly and you know it.",
        "Pack a gym bag tonight so you can go straight to the gym tomorrow without inventing new excuses.",
        "Book a dental cleaning in the next six weeks before the reminder postcard disappears under mail.",
        "Try a ten-minute guided breathing exercise before your hardest meeting and rate anxiety from one to ten.",
        "Replace running shoes if mileage is over four hundred miles and break them in on short walks first.",
    ],
    "home": [
        "Deep-clean the fridge shelves before Saturday groceries so nothing hides behind expired condiments.",
        "Replace HVAC filters using the size on your phone photo and set a quarterly calendar reminder.",
        "Fix the wobbly dining chair by tightening screws and gluing the loose joint before guests arrive.",
        "Run bedding on hot and air-dry pillows outside if the weather is sunny for once this weekend.",
        "Test every smoke detector and change batteries wherever one chirped at three a.m. last week.",
        "Patch the small hole behind the door and touch up paint so the wall stops catching your eye daily.",
        "Organize the junk drawer with tiny bins labeled tape, batteries, and cables you might actually need.",
        "Vacuum under the couch cushions and drop the coins in the jar on the counter like a small win.",
        "Schedule bulk trash pickup for the broken chair before the HOA sends another passive-aggressive email.",
        "Wipe the microwave with lemon steam before your in-laws visit on Saturday afternoon without drama.",
    ],
    "family": [
        "Email your kid's teacher to confirm the field trip permission slip is signed and uploaded before Friday.",
        "Plan a screen-free board game night next Friday and buy snacks everyone already voted on in chat.",
        "Book a pediatric well visit before kindergarten registration deadlines sneak up while you blink.",
        "Call your parents for thirty minutes on Sunday at ten a.m. their time and listen without multitasking.",
        "Create a shared summer camp spreadsheet with carpool shifts so one parent does not burn out alone.",
        "Pack healthy lunchboxes Sunday night with ice packs so Monday morning feels ten percent less chaotic.",
        "Update the emergency card in each backpack with the new pediatrician number before school Tuesday.",
        "Book date night childcare before you lock the nonrefundable dinner reservation downtown this month.",
        "Photograph the kids' artwork backlog and recycle originals after you save digital copies somewhere safe.",
        "Write a short bedtime routine checklist with pictures so the toddler stops fighting every transition.",
    ],
    "learning": [
        "Finish module four of your online course including quizzes before the Sunday night deadline hits.",
        "Reserve a quiet library room Saturday morning to draft the essay introduction without your phone nearby.",
        "Email the professor one specific question about the proof you are stuck on after page six tonight.",
        "Make forty flashcards from this week's slides and review them on the bus both ways on Monday.",
        "Skim three abstracts and write one paragraph each on why they matter for your thesis thread.",
        "Set eight Pomodoro timers today and spend them only on problem set three corrections until done.",
        "Watch the assigned lecture at one point two five speed, pause for notes, then rewrite them cleanly.",
        "Apply for the small department grant whose portal closes Thursday at eleven fifty-nine p.m. your time.",
        "Organize PDFs into a folder named by week so Downloads stops eating your sanity every finals season.",
        "Join study group voice at eight p.m. sharp and mute side chats during sprint blocks like you promised.",
    ],
    "fun": [
        "Buy concert tickets for May before presale ends and add parking details to your calendar note.",
        "Invite two friends to the new board cafe Saturday at seven and reserve a table online tonight.",
        "Plan a tourist-in-your-own-city afternoon with three stops and one dessert you rarely allow yourself.",
        "Queue three comfort movies for a rainy Sunday and prep popcorn toppings you do not usually splurge on.",
        "Book a beginner pottery class next month and read the cancellation policy before you pay the deposit.",
        "Research a shady four-mile hike and download offline maps before you lose signal on the trailhead.",
        "Try one new recipe from a cuisine you rarely cook and plate it like you mean it for dinner tonight.",
        "Schedule a video game night with cross-platform friends and test voice chat an hour before start.",
        "Buy cheap tickets to a minor-league game and plan transit so you are not late to first pitch Sunday.",
        "Make a summer bucket list with ten items and circle three you will actually schedule before July ends.",
    ],
    "growth": [
        "Write one page on what last week's mistake taught you and file it where only you will reread it.",
        "Message a mentor for twenty minutes next week with two questions you already wrote on a sticky note.",
        "Update your portfolio site with latest screenshots and fix the broken outbound project links tonight.",
        "Schedule a quarterly review with yourself covering wins, losses, habits to stop, and one bold experiment.",
        "Read one long article outside your field and summarize it in five bullets inside your notes app.",
        "Practice a hard conversation out loud for ten minutes and note where your tone gets defensive halfway.",
        "Enroll in the public speaking workshop before the early-bird discount ends this Friday at midnight.",
        "Draft a personal mission statement under one hundred words and pin it above your desk for edits.",
        "Block Saturday morning for quiet journaling with three prompts you bookmarked months ago on purpose.",
        "Delete three apps that fragment your attention and log how you feel after seven days without them.",
    ],
    "money": [
        "Move two hundred dollars into your emergency fund after double-checking routing numbers one last time.",
        "Dispute the duplicate streaming charge and attach screenshots of both bills inside the bank portal.",
        "Export tax documents from payroll into the folder your accountant shared before Thursday's call.",
        "Call your phone carrier with a competitor quote written down before you give up on hold music again.",
        "Review credit card reward categories and move recurring bills to the card that pays three percent back.",
        "Build a simple April budget and reconcile every category against what you actually spent last month.",
        "Set autopay on utilities that still charge late fees when you forget the due date like clockwork.",
        "Compare car insurance quotes from two brokers and switch if savings beat one hundred twenty per year.",
        "Read your four oh one k fund expense ratios and decide whether you will rebalance next quarter calmly.",
        "Schedule a thirty-minute fee-only advisor call to sanity-check your retirement contribution rate soon.",
    ],
    "creativity": [
        "Sketch ten thumbnails for the poster commission before you pick two to refine digitally on Sunday.",
        "Rewrite your short story opening in a different tense and read both versions aloud to hear the shift.",
        "Organize reference images into a mood board folder and label each file with one emotion keyword.",
        "Block three hours in the studio with your phone off until the glazing on those pieces is finished.",
        "Film a rough process video of your workflow and trim it under ninety seconds for social tomorrow.",
        "Critique your last piece with a rubric you trust and list five concrete fixes you can ship this week.",
        "Research copyright-safe music for your reel and save licenses in a dated subfolder like a grown-up.",
        "Back up Procreate files to cloud storage and delete old versions you will honestly never reopen.",
        "Email the gallery about submission specs including frame size before the winter show deadline passes.",
        "Spend twenty-five minutes on blind contour warm-ups before you touch the real portrait session Sunday.",
    ],
    "community": [
        "Sign up for the park cleanup on Earth Day and pack gloves plus a water bottle in your tote tonight.",
        "Donate five gently used coats to the downtown drive and grab a receipt if taxes might care later.",
        "RSVP yes to the neighborhood meeting and skim the agenda PDF before you walk in feeling lost.",
        "Volunteer to bring name tags and a sign-in sheet for the PTA meeting you already planned to attend.",
        "Introduce two friends who should collaborate with a warm three-sentence email that names why they click.",
        "Offer to mentor a junior for four thirty-minute coffees and block them on recurring Friday mornings.",
        "Share the mutual aid spreadsheet with three neighbors who might not be in the group chat yet.",
        "Help set up chairs for the community concert and stay for teardown so organizers can actually go home.",
        "Research local ballot measures and write a cheat sheet for friends who vote on Sunday afternoon.",
        "Organize a one-block potluck with a signup for mains, sides, and allergy notes before you invite everyone.",
    ],
    "well-being": [
        "Turn off all screens sixty minutes before bed tonight and read fiction only under warm lamplight.",
        "Schedule a therapy session two weeks out if your last visit was more than a month ago already.",
        "Take a twenty-minute walk without headphones and notice five sounds you usually tune out completely.",
        "Write a boundaries text about after-nine work texts and send it kindly before resentment builds more.",
        "Book a massage after the stressful project milestone you already know is coming next week.",
        "Try five minutes of box breathing before your hardest meeting and rate anxiety from one to ten honestly.",
        "Journal three gratitudes and one worry dump page, then tear the worry page into tiny pieces tonight.",
        "Charge your phone outside the bedroom and buy a cheap alarm clock so sleep stops losing to scrolling.",
        "Block nothing time on Sunday afternoon with no plans except tea and staring out the window guilt-free.",
        "Email your doctor about the side effect you have been downplaying since January like it matters.",
    ],
    "sports": [
        "Wash and air-dry gym clothes tonight so tomorrow's workout bag does not smell sour in the locker room.",
        "Book court time for doubles next Thursday and text your partner to confirm footwork drills beforehand.",
        "Replace cleats if studs look uneven and break them in on grass before the league game Saturday.",
        "Schedule sports massage the week after your half if your hamstring felt tighter than it should.",
        "Film your swing from two angles and compare to last month so you pick one cue to fix at the range.",
        "Pack electrolytes and sunscreen for Saturday's tournament and set two alarms so you are not late.",
        "Stretch calves and IT band for fifteen minutes after today's run and log mileage in your app tonight.",
        "Order replacement goggles before the meet because the strap is fraying at the buckle already.",
        "Watch film of last game's third quarter and note three defensive mistakes with timestamps like a coach.",
        "Hydrate with electrolytes if practice is in heat and be honest about dizziness before you push harder.",
    ],
    "travel": [
        "Confirm hotel check-in time and parking height before you drive the tall SUV into the garage ramp.",
        "Download offline maps for the whole island and star breakfast spots within walking distance tonight.",
        "Renew your passport if it expires within nine months of your international return date on paper.",
        "Pack chargers in carry-on inside a labeled pouch and photograph bag contents for insurance if needed.",
        "Email the airline about seat preference for the long leg and mention the bassinet note if it applies.",
        "Convert three hundred dollars to local currency at your bank this week to skip airport kiosk rates.",
        "Add travel insurance policy numbers to your phone's medical ID note before you leave the country.",
        "Print the rental agreement PDF and highlight the fuel policy so the desk argument does not happen.",
        "Schedule a pet sitter walk-through and tape typed feeding instructions on the fridge before you leave.",
        "Make a rainy day three-museum plan for day three so weather does not wreck the whole vacation mood.",
    ],
    "entertainment": [
        "Finish season two episode eight tonight without spoilers and post a vague reaction in the group chat.",
        "Buy advance tickets for the indie screening Sunday and invite the friend who loves that director most.",
        "Curate a twelve-song commute playlist themed around songs that feel like neon under streetlights.",
        "Read one long interview with the showrunner and save the best quote into your notes app tonight.",
        "Schedule a finale watch party with snack assignments so you are not carrying everything alone again.",
        "Cancel the streaming service you have not opened in six months after you export your watchlist safely.",
        "Rewatch the pilot with director commentary and jot three craft choices you never noticed the first time.",
        "Research whether the book adaptation is faithful enough to read chapters one through five before nine.",
        "Organize Blu-rays alphabetically and sell two duplicates on marketplace before shelves groan louder.",
        "Set a bedtime alarm so binge-watching does not steal sleep on a work night like last Tuesday did.",
    ],
    "fitness": [
        "Book a personal training intro at the gym near work and ask for form checks on deadlifts politely.",
        "Program progressive overload for squats for four weeks and pencil a deload week five like adults do.",
        "Schedule a rest day with active recovery like a twenty-minute walk plus hip and thoracic mobility.",
        "Order new running socks because the pair that gives blisters on long Sundays is not worth loyalty.",
        "Sign up for the Thanksgiving five K and add three short tempo runs to your calendar before October.",
        "Film your plank form and compare elbow alignment to a trainer video you actually trust on YouTube.",
        "Meal prep four lunches with thirty grams of protein so afternoon lifts do not feel bonk-prone again.",
        "Hydrate with electrolytes if you train in heat and be honest about urine color in your log tonight.",
        "Book a bike tune-up before the century ride and ask them to true both wheels while you wait.",
        "Stretch hip flexors for eight minutes after sitting meetings if you want squat depth back this month.",
    ],
    "career": [
        "Update your LinkedIn headline with quantified impact and turn on recruiter visibility if you dare.",
        "Schedule informational coffee with the alum who works at the company you are quietly targeting.",
        "Rewrite resume bullets in STAR format and tailor one page to the posting keywords before you apply.",
        "Prepare five behavioral interview stories and practice them aloud under ten minutes each tonight.",
        "Send thank-you emails within twenty-four hours referencing one specific moment from each interview.",
        "Ask your manager for written promotion criteria and add quarterly milestones to your shared doc.",
        "Research salary bands on three sites and draft a negotiation script before the offer call on Friday.",
        "Polish your GitHub readme with setup steps, screenshots, and a working link to the live demo build.",
        "Buy a conference ticket before early bird ends and submit talk proposal draft version two tonight.",
        "Clean up Slack profile photo and status so new cross-functional partners see intention instead of chaos.",
    ],
    "friends": [
        "Text the friend you ghosted since January, apologize briefly, and propose tacos next Wednesday night.",
        "Plan a low-key picnic Saturday at eleven with a shared note for who brings drinks versus snacks.",
        "Buy a birthday gift online with guaranteed Thursday delivery and wrap it Sunday while you watch TV.",
        "Schedule a video call with your college roommate in another time zone before their big interview.",
        "Organize game night RSVP list and cap it at six so nobody sits out awkward rounds on the couch.",
        "Send voice memos instead of texts for three days to one friend who genuinely prefers audio catch-ups.",
        "Mail a handwritten thank-you for last month's favor and include a silly inside joke sticker inside.",
        "Create a shared album from the trip and tag everyone before the memories blur into vague vibes.",
        "Offer to dog-sit the weekend your friend has surgery and confirm fence height for the escape artist.",
        "Block monthly friend-maintenance Friday lunches so they stop slipping off the calendar every season.",
    ],
    "rest": [
        "Turn on Do Not Disturb from nine p.m. to seven a.m. for a week and delete Slack from your phone.",
        "Schedule a true no-plans Saturday with no chore list, just books, tea, and maybe a short walk outside.",
        "Buy blackout curtains or fix the gap where streetlight hits your pillow at five forty-five a.m.",
        "Try a twenty-minute nap with the alarm across the room and note energy before evening plans honestly.",
        "Delete social apps for three days and replace scrolling with a paper novel on the nightstand instead.",
        "Book a quiet cabin within ninety minutes for a solo reset weekend before burnout gets louder inside.",
        "Write a not-doing list for Sunday listing work tasks you refuse to touch even if guilt whispers.",
        "Listen to one album start to finish with eyes closed instead of algorithmic playlists that scatter you.",
        "Take a bath with epsom salts and leave the phone in another room for the whole soak like you mean it.",
        "Tell your partner you need one hour alone behind a closed door tonight without sounding like a villain.",
    ],
    "food": [
        "Meal plan five dinners, build the cart, and schedule Saturday ten to eleven a.m. pickup before slots vanish.",
        "Batch-cook two soups Sunday afternoon and freeze half in labeled quart containers dated with today's date.",
        "Sharpen knives or drop them at the farmers market sharpener before you dice tomatoes Wednesday night.",
        "Clean fridge door shelves and toss condiments you have not touched since last Thanksgiving honestly.",
        "Try one new spice in a familiar recipe and write tasting notes so you remember next month's attempt.",
        "Reserve a table for four at the new restaurant before reviews make weekend bookings impossible online.",
        "Organize pantry into zones for baking, snacks, and grains, then donate duplicates to the food bank.",
        "Prep overnight oats in jars for three mornings so you stop skipping breakfast before work again.",
        "Research a summer CSA box and compare pickup distance to your commute before you commit money.",
        "Schedule a grocery audit where you photograph staple prices at two stores you actually shop weekly.",
    ],
    "music": [
        "Practice scales at sixty BPM with a metronome for fifteen minutes before you touch repertoire pieces.",
        "Book the community practice room for Sunday three p.m. and bring sheet music in a real folder.",
        "Restring your guitar before open mic because the high E keeps slipping at the second fret again.",
        "Transcribe the solo at half speed and mark fingerings in pencil before you ink anything permanent.",
        "Update the band Linktree with the new single presave link and click every outbound URL once tonight.",
        "Schedule ear-training drills for ten minutes daily this week and log your streak on paper like old school.",
        "Back up Logic projects to an external SSD and delete bounced duplicates so disk space stops gasping.",
        "Email the venue about backline availability and attach your stage plot PDF with the input list clear.",
        "Listen critically to one reference track and EQ-match your rough mix for five narrow bands only.",
        "Pack earplugs and a tuner for rehearsal and text the drummer to confirm load-in time before Friday.",
    ],
    "reading": [
        "Finish chapters twelve through fourteen tonight and write three margin questions for book club Tuesday.",
        "Return library books due Monday and renew the one you are halfway through before fines appear.",
        "Order the sequel in paperback because you annotate physical pages better for thesis notes this term.",
        "Schedule a forty-five-minute reading block before bed with the phone charging in the kitchen drawer.",
        "Summarize the article you saved last month in your own words and file it in your research vault tonight.",
        "Join the author's online Q and A and submit one thoughtful question that cites page eighty-seven directly.",
        "Clean your e-reader highlights export and tag quotes by theme for the lit review section this weekend.",
        "Read one poem aloud to someone you live with and ask which image stuck with them afterward.",
        "Donate five books you will not reread and photograph the shelf gap so motivation stays visible.",
        "Preload tomorrow's audiobook chapter and set playback to one point one if the narrator drags slightly.",
    ],
    "art": [
        "Prime the small canvas tonight so it is dry before Saturday plein air when humidity might spike.",
        "Photograph your latest piece in indirect daylight and color-correct one hero image for your portfolio.",
        "Mix a limited palette of five tubes and paint a still life using only those for discipline this week.",
        "Visit the museum on free Thursday and sketch three compositions in a pocket notebook without talking.",
        "Frame the finished work with UV glass before the client pickup appointment next Wednesday afternoon.",
        "Organize tubes by warm and cool and label opened dates so you stop buying duplicate cadmium red.",
        "Schedule a portfolio review and send PDFs forty-eight hours early like the email politely requested.",
        "Clean brushes with soap and reshape tips before they splay permanently and waste good hair.",
        "Research local call-for-artists deadlines and draft a two-hundred-word artist statement before bed.",
        "Back up high-res scans to two places because last drive failure taught you humility the hard way.",
    ],
    "nature": [
        "Identify five plants on your walk with an app and save screenshots to a local flora album tonight.",
        "Schedule a sunrise hike Sunday and check the layered clothing forecast the night before honestly.",
        "Water new trees deeply twice this week because the heat wave is stressing the youngest saplings out.",
        "Clean and oil pruners after rose pruning so disease does not hitchhike to the tomato bed tomorrow.",
        "Research native pollinator seeds for your zone and order from a reputable nursery instead of big-box impulse.",
        "Pack a trash bag on the trail walk and pick up litter for twenty minutes like a micro volunteer.",
        "Book campsite B seven for Memorial Day weekend before the reservation site crashes at seven a.m. open.",
        "Check tide tables for Saturday clamming and buy the license online if your state still requires it.",
        "Turn compost with a fork and add browns because the pile smells too wet after last week's rain.",
        "Photograph the feeder bird, crop it, and submit the checklist entry before you forget the species name.",
    ],
    "projects": [
        "Write acceptance criteria for ticket two zero four before standup so QA stops reopening it weekly.",
        "Schedule a forty-five-minute risk review with the PM and attach the dependency sketch you drew.",
        "Cut scope on the animation so the May twelfth launch stays realistic without burning the team out.",
        "Update the readme install steps after the Node upgrade broke three teammates yesterday afternoon.",
        "Create a rollback checklist for Thursday deploy and rehearse it once on staging like you mean it.",
        "Email stakeholders a one-pager with green yellow red, decisions needed, and asks due by Friday noon.",
        "Pair with the junior for ninety minutes on flaky tests until CI stays green for two runs straight.",
        "Document the API contract change in Notion and ping consumers in Slack with a migration timeline.",
        "Close duplicate GitHub issues and label the rest with priority and owner so triage stops feeling personal.",
        "Block focus time to finish the demo script before the exec review at two p.m. tomorrow without excuses.",
    ],
    "hobbies": [
        "Wind a fresh bobbin before the quilt border so tension issues do not ruin Saturday sewing plans.",
        "Oil the sewing machine and swap to a denim needle before hemming jeans that fray every wash.",
        "Organize yarn by weight and photograph your Ravelry queue so you stop rebuying the same skein colors.",
        "Book a makerspace laser slot with a certified buddy because solo certification still scares you slightly.",
        "Finish sanding miniature bases before primer because dust specks ruin scale realism under bright lights.",
        "Research safe enamel firing temps and tape them above the kiln switch where panic looks first.",
        "Pack model tools in a hard case before the IPMS meet so nothing bends in transit like last time.",
        "Watch one technique video for the skill you avoid and practice it twenty minutes only without spiraling.",
        "List three half-finished projects and pick one to finish before you buy any new supplies this month.",
        "Photograph the finished piece for insurance inventory and add a serial note to the spreadsheet row.",
    ],
    "social": [
        "Send paper invites for the housewarming with RSVP two weeks before you order catering portions.",
        "Create a shared album from the party before people forget to AirDrop their favorite blurry shots.",
        "Plan seating for twelve with two vegetarians and one nut allergy noted for the chef email tonight.",
        "Buy thank-you cards tonight and mail them within a week for gifts you already opened at the party.",
        "Schedule coffee with the new neighbor Wednesday and bring muffins from the bakery you actually like.",
        "Pin a short group-chat message about respectful disagreement before drama spirals again this month.",
        "Build a volunteer shift swap sheet so last-minute cancels do not strand the same person every time.",
        "Decline the third overlapping event politely and protect one empty evening for yourself without guilt.",
        "Host game night by assigning chips, drinks, and ice so you are not carrying everything alone again.",
        "Follow up individually with three quieter guests who seemed left out at the last gathering honestly.",
    ],
    "spirituality": [
        "Sit twenty minutes in silence before work using only a timer app without a guided voiceover track.",
        "Read one short sacred chapter and copy one verse into your journal in your own handwriting tonight.",
        "Schedule temple volunteering next month and add it to the shared family calendar before you forget.",
        "Write a forgiveness letter you will not send and shred it as a symbolic release ritual after dinner.",
        "Walk a labyrinth or quiet park path slowly without your phone and notice three sensory details aloud.",
        "Donate anonymously online to the cause you care about instead of only resharing posts that fade fast.",
        "Fast from gossip for a week and note when your urge to criticize coworkers spikes at standup.",
        "Attend study group Zoom with camera on and one prepared question about the reading like you promised.",
        "Dust the meditation corner, replace dried flowers, and recharge the singing bowl mallet before Sunday.",
        "Set your lock screen to a mantra you chose on purpose so you see it before doomscrolling again.",
    ],
    "movies": [
        "Watch the director's first feature tonight and note three stylistic choices that repeat in their work.",
        "Buy IMAX tickets before they sell out and pick seats away from the subwoofer that rattles your ribs.",
        "Read one spoiler-free review and decide if theaters are worth it or if rental patience wins tonight.",
        "Schedule a double feature at home with intermission snacks planned so pauses feel intentional not awkward.",
        "Update Letterboxd with honest half-star ratings and follow three critics whose taste actually matches yours.",
        "Clean remote batteries and HDMI inputs before movie night because audio cut out last time embarrassingly.",
        "Match TV aspect ratio to the classic film you rented instead of stretching faces like last weekend.",
        "Invite a friend who hates the genre and trade one pick each for compromise night with popcorn rules.",
        "Turn on English subtitles because dialogue was muddy on the soundbar and you missed the twist line.",
        "Pack a light jacket for the late show because theater AC is always set to arctic no matter the season.",
    ],
    "comedy": [
        "Buy tickets for the local standup showcase Friday and arrive thirty minutes early for decent seats.",
        "Watch one new special with the notebook closed first, then rewatch the first ten minutes for timing study.",
        "Sign up for beginner improv whose waitlist opens Monday and set a calendar alarm so you do not miss it.",
        "Transcribe one favorite minute and mark breaths and tags on paper before you rewrite your own set.",
        "Email open mic signup Tuesday at nine a.m. because slots fill in minutes every single week downtown.",
        "Record a three-minute practice set on your phone, listen once cringing, then delete if it is truly bad.",
        "Research clean versus dirty rooms before booking the one that matches your material style honestly.",
        "Invite two friends to a club with a two-drink minimum noted so nobody is surprised at the check.",
        "Follow three working comics for gig announcements instead of only famous headliners you already know.",
        "Pack cough drops and water for laugh-heavy shows that dry your throat before the second act starts.",
    ],
    "shows": [
        "Finish episode six before Tuesday's group chat deadline so nobody spoils the cliffhanger on purpose.",
        "Create a shared watching schedule with your partner capped at two episodes per night to avoid fatigue.",
        "Read the wiki recap only after watching because last time spoilers ruined the twist you waited months for.",
        "Cancel the subscription after the season ends and set a reminder to resubscribe when the next drops.",
        "Buy snacks before pressing play so you are not pausing at the worst emotional beat like last Sunday.",
        "Schedule a finale watch party with one agreed bathroom break at the midpoint of the long episode.",
        "Turn off motion smoothing before the cinematography-heavy drama because soap opera mode ruins it.",
        "Update your tracking sheet with runtimes so you know if tonight fits before bed like an adult.",
        "Listen to the official podcast episode tied to chapter seven only after you finish that chapter.",
        "Archive screenshots of favorite quotes into a folder because you will want them for fan art later.",
    ],
    "exercise": [
        "Book a yoga class for tomorrow morning and pack mat and towel in the car tonight without debating.",
        "Schedule a bike fit if knee pain returns after rides longer than ninety minutes like last spring did.",
        "Program treadmill intervals of two minutes hard and ninety seconds easy times eight and screenshot stats.",
        "Buy replacement resistance bands because the medium snapped mid-pull and that was honestly scary.",
        "Add foam rolling hips and spine to cooldown every gym day for two weeks and log pain from one to ten.",
        "Reserve the swim lane at six thirty Tuesday and set two alarms across the room so you actually go.",
        "Research Couch to five K if you have not run consistently since college and be kind to your ankles.",
        "Pack a clean mask, lock, and charged headphones before work meetings stack and steal your evening.",
        "Stretch calves on the curb after every run this week because Achilles tightness came back quietly.",
        "Put an honest rest day on the calendar so exhaustion stops masquerading as laziness in your head.",
    ],
    "study": [
        "Finish calculus problems twelve through eighteen before Canvas locks at midnight like it always does.",
        "Rewrite lecture notes into Cornell format for chapter five before Friday's quiz covers it without mercy.",
        "Reserve library room Sunday two to five with phone in locker for deep focus on the lab report.",
        "Email the TA one specific question about the board photo from page two attachment before office hours.",
        "Create Anki cards for chapter eight vocabulary and review on the bus both ways like you planned Monday.",
        "Simulate exam conditions for fifty minutes with no notes, then grade with the rubric harshly once.",
        "Organize PDFs in weekly folders so search stops failing every time finals season panic returns.",
        "Join study Discord voice at eight sharp and mute side chats during Pomodoro sprints without cheating.",
        "Print practice exams duplex to save paper and mark answers lightly if you need a second pass Sunday.",
        "Sleep eight hours before the midterm because all-nighters hurt grades more than cram helps anyone.",
    ],
    "school": [
        "Submit the scholarship essay draft to the writing center before Friday's midnight portal locks you out.",
        "Email the professor about the excused absence form before the registrar cutoff next Wednesday afternoon.",
        "Buy lab goggles that meet syllabus spec and stash them in your backpack pocket so you never forget.",
        "Schedule advisor summer credits confirmation before your intended major track quietly changes again.",
        "Print the poster at campus shop Tuesday pickup because FedEx lines are insane during presentation week.",
        "Update Canvas notifications so assignment drops do not ambush you at eleven fifty-eight p.m. again.",
        "Return the rental textbook with the shipping label taped outside before late fees hit Monday morning.",
        "Organize club budget Venmo screenshots for September reimbursements before the treasurer chases you.",
        "Book campus health flu walk-in Thursday between classes with buffer time so you are not late.",
        "Rewrite resume bullets with the career center template before Thursday career fair booths open.",
    ],
    "research": [
        "Fix BibTeX citation keys for the three sources reviewers flagged before you resubmit the manuscript.",
        "Email your collaborator the cleaned dataset changelog before they rerun regressions overnight again.",
        "Schedule lab meeting to present figure four alternatives because the PI hated yesterday's color scale.",
        "Back up raw instrument files to the institutional server before deleting local copies per compliance.",
        "Draft the methods exclusion paragraph with exact N at each filtering step so reviewers stop guessing.",
        "Update preregistered analysis text if the pilot changed your primary outcome more than you admitted.",
        "Read two opposing papers and build a synthesis table comparing assumptions row by row tonight.",
        "Transcribe key numbers from notebook photos into the master spreadsheet before the PI meeting Friday.",
        "Submit the IRB amendment for survey wording before you collect the next hundred responses online.",
        "Block three hours to debug the merge bug that duplicates rows on participant ID like a nightmare.",
    ],
    "deadlines": [
        "Send the revised client PDF by five p.m. Tuesday and request a read receipt if their inbox is chaos.",
        "Break the grant proposal into six Pomodoros and finish the budget justification section tonight early.",
        "Warn your manager today if the vendor slip means Friday ship is unrealistic before promises harden.",
        "Upload the signed contract scan before the portal auto-cancels the offer at eleven fifty-nine tonight.",
        "Schedule a buffer day before launch for smoke tests you always skip and always regret skipping later.",
        "Email legal three numbered questions about clause eight point two before you sign electronically tonight.",
        "Put deliverables in a checklist with owner and due date columns shared at the top of the project doc.",
        "Proofread the deck aloud to catch awkward phrasing on slide fourteen before the exec sees it live.",
        "Set a phone alarm one hour before UTC cutoff so timezone math does not ruin another submission.",
        "Buy fancy coffee after you hit submit even if the results are still unknown because you earned it.",
    ],
    "homework": [
        "Finish calculus twelve through eighteen and upload clear scan work before Canvas locks at midnight.",
        "Rewrite the history essay intro using teacher comments and book writing center Wednesday at four p.m.",
        "Read biology chapter twenty-two section three and answer end questions in complete sentences tonight.",
        "Book a tutor Sunday if stoichiometry is still blank after two honest attempts without shame spiraling.",
        "Print graph paper at the library because crooked axes on notebook paper looked unprofessional last time.",
        "Nudge your group partner politely with bullets for their two overdue slides before class tomorrow.",
        "Sharpen pencils, replace calculator batteries, and hole-punch loose sheets before the midterm room opens.",
        "Study Spanish vocab with voice memos on the walk without looking at your phone because safety matters.",
        "Submit lab notebook photos with legible labels before TA office hours close tomorrow afternoon honestly.",
        "Lay out clothes, set three alarms across the room, and charge your phone away from the bed tonight.",
    ],
    "meetings": [
        "Send agenda bullets by five p.m. today so introverts can prepare talking points before tomorrow morning.",
        "Pre-read the twelve-page memo and highlight three questions you will ask in the first ten minutes live.",
        "Book the conference room with HDMI reserved and test screen share five minutes early like a pro.",
        "Assign a note-taker and timekeeper in the calendar invite so chaos does not eat half the hour again.",
        "Send a summary email within twenty-four hours listing decisions, owners, and due dates only, no fluff.",
        "Decline the overlap with a polite conflict note and propose two alternate thirty-minute windows tomorrow.",
        "Record action items live in the shared doc instead of trusting memory across eight distracted brains.",
        "Mute notifications during deep work after stacked meetings turned you reactive for the whole afternoon.",
        "Schedule a walking one-on-one for relationship repair because Zoom felt too cold last quarter honestly.",
        "Cancel the recurring meeting with no agenda three weeks running and replace it with an async doc link.",
    ],
    "email": [
        "Unsubscribe from five newsletters you skim-delete every morning and keep the one you truly read weekly.",
        "Create three inbox rules to auto-label receipts, travel, and HR so search stops failing every April.",
        "Draft a polite decline to the committee you cannot join and suggest another qualified colleague by name.",
        "Check email only at ten a.m. and three p.m. this week so afternoon coding stops fragmenting into crumbs.",
        "Empty the promotions tab and archive anything older than ninety days unless legal says you cannot.",
        "Update your signature with the correct title and remove the broken Calendly link before clients notice.",
        "Send a follow-up on the stalled thread with a tight recap bullet list and one clear ask by Friday.",
        "Export important threads to PDF for the binder before the vendor domain disappears without warning.",
        "Fix the vacation auto-reply dates because last year's typo embarrassed you in front of half the company.",
        "Print two-factor backup codes tonight and tuck them in the fireproof box with your passport copy.",
    ],
    "coding": [
        "Open a pull request that fixes the flaky test by mocking network and tag the backend owner for review.",
        "Refactor the four-hundred-line module into two files with zero behavior change and green CI only.",
        "Document environment variables in dot env example with comments so onboarding stops taking three days.",
        "Schedule a pair session to reproduce the Safari-only race before Friday's launch window feels scary.",
        "Close security dependabot alerts after reading changelogs instead of blindly merging everything green.",
        "Add logging around the payment webhook before Friday launch because support dreads silent failures nightly.",
        "Write rollback steps in the ticket body so on-call is not guessing at three a.m. with tired eyes.",
        "Benchmark the hot path with realistic data size and attach the graph screenshot to the perf issue.",
        "Delete dead feature flags after two stable releases and remove unreachable code paths without drama.",
        "Update readme troubleshooting with the SSL fix that stole four hours of your life you will not repeat.",
    ],
    "writing": [
        "Rewrite your article lede three ways and pick the one that passes the read-aloud test on your porch.",
        "Interview source B before Tuesday because source A ghosted and the deadline is genuinely non-negotiable.",
        "Fact-check every statistic in paragraph two with primary links saved in the footnotes doc tonight.",
        "Schedule a writing sprint Saturday eight to eleven with internet blocked except the dictionary site.",
        "Send the pitch email with three headline options and a one-sentence nut graf only, no attachment yet.",
        "Outline chapter seven beats on index cards and rearrange until the emotional arc feels honest not clever.",
        "Run a grammar pass focused only on tense consistency because beta readers flagged time travel whiplash.",
        "Save versioned filenames with dates so you stop overwriting the draft that actually worked last Tuesday.",
        "Read submission guidelines twice and format the manuscript exactly including the weird font rule page.",
        "Reward yourself with fancy tea only after one thousand words today because bribery still works sometimes.",
    ],
    "gaming": [
        "Back up save files for the RPG before patch day because last update corrupted your forty-hour run cruelly.",
        "Schedule LAN Saturday: test ping, update drivers, and download the day-one patch Friday night early.",
        "Finish the side quest chain before the main story point of no return because the wiki warned you twice.",
        "Clean controller sticks with isopropyl because drift is ruining your ranked climb tonight embarrassingly.",
        "Read the Steam refund window before buying early access that might ship broken and break your heart.",
        "Mute toxic voice chat and bind push-to-talk so you stop broadcasting keyboard noise to strangers online.",
        "Organize the mods folder and remove conflicts causing crashes on the load screen after the logo appears.",
        "Set an honest timer if work deadlines mean gaming should not start until nine p.m. without negotiation.",
        "Watch a pro replay of your main and note three positioning mistakes with timestamps like you coach kids.",
        "Pack portable monitor and HDMI cable for tournament day because venue supply is never guaranteed ever.",
    ],
    "cooking": [
        "Brine the chicken two hours before roast per recipe and set the meat thermometer alarm to one sixty-five.",
        "Sharpen the chef knife or drop it at the farmers market booth before dicing onions for Sunday soup.",
        "Build the grocery list from five dinner recipes and check the pantry for duplicates before you shop.",
        "Clean fridge shelves before new produce arrives so nothing hides behind expired jars of mustard again.",
        "Prep mise en place bowls before stir-fry because last time garlic burned while you were still chopping peppers.",
        "Label freezer containers with date and contents so mystery soup stops happening every April thaw season.",
        "Watch one knife skills video for twenty minutes before julienne for guests this weekend without rushing.",
        "Buy a spare propane tank before Memorial Day grill season because stores sell out every single year.",
        "Halve the air fryer recipe on the first trial because reviews say it overflows when you are greedy.",
        "Wash dishes immediately after cooking tonight so tomorrow morning you does not hate tonight you again.",
    ],
    "pets": [
        "Book the annual vet visit including heartworm test before the kennel requires paperwork next month.",
        "Order prescription diet kibble before you run out mid-week because shipping takes five days every time.",
        "Brush the shedding dog outside twice this week and vacuum the filter after because allergies spiked again.",
        "Book a dog walker trial Thursday if new job hours mean lunch walks are impossible without guilt spirals.",
        "Deep-clean the litter box and replace the carbon filter because apartment smell is getting noticeable now.",
        "Update the microchip registry address after your move because the old city still shows on every scan.",
        "Pack travel water bowl and poop bags in the car door pocket before Saturday road trip departure time.",
        "Read groomer reviews for mat removal and confirm they handle anxious dogs with breaks like you need.",
        "Set a thyroid pill alarm for the cat because missed doses really matter more than denial wants to admit.",
        "Photograph the new lump with a coin for scale and email the vet photo tonight instead of hoping it vanishes.",
    ],
    "garden": [
        "Water raised beds deeply morning and evening during the heat wave and mulch so evaporation slows down.",
        "Prune dead wood from the rose bush before fungal spores spread and disinfect shears between every cut.",
        "Start tomato seeds indoors under grow lights six weeks before your zone's last frost date on paper.",
        "Test soil pH with the co-op kit and amend bed B with lime only if results say you are too acidic.",
        "Replace irrigation timer batteries and walk every zone to unclog emitters before July heat peaks hard.",
        "Harvest zucchini before baseball bat size and shred extras into fritters for the freezer this weekend.",
        "Order beneficial nematodes for grubs and apply evening per the package instructions without improvising.",
        "Oil the pruner pivot because sticky blades caused uneven cuts that stressed the hydrangeas last month.",
        "Plan fall bulb orders before the summer sale ends and tape planting depth chart on the garage wall.",
        "Weed the north bed thirty minutes after rain when roots slide out easier and dust stays down lower.",
    ],
    "budget": [
        "Reconcile March credit transactions and rename anything still labeled miscellaneous before April closes.",
        "Call internet retention with a competitor quote on paper before you chicken out on hold music again.",
        "Move one hundred fifty dollars to the car insurance sinking fund because August will arrive without warning.",
        "Export tax donation receipts into one PDF folder before the accountant meeting Thursday morning early.",
        "Cancel the Adobe trial on day six because you only needed one export and pride is cheaper than fees.",
        "Review mortgage escrow analysis if last month's payment jumped mysteriously on the statement line items.",
        "Submit HSA reimbursement for reading glasses with receipt photos before the portal window closes Friday.",
        "Build a simple debt snowball sheet sorted by interest rate and smallest win first like the book says.",
        "Set a calendar alert three days before every free trial ends because surprise charges still sting monthly.",
        "Negotiate a medical bill payment plan after comparing itemized charges to the insurer explanation carefully.",
    ],
    "side projects": [
        "Renew domain privacy before spam harvesters scrape your WHOIS email into another miserable sales funnel.",
        "Deploy the landing page to staging and send a test link to two friends for brutal honest feedback tonight.",
        "Write a readme with screenshots and a why-this-exists paragraph before you share the repo on Twitter.",
        "Block two hours Sunday to wire consistent analytics event names across pages before launch feels sloppy.",
        "Close twelve stale GitHub issues and label good-first-issue for newcomers who might actually show up.",
        "Record a sixty-second demo with captions because silent autoplay social prefers subtitles every single time.",
        "Research competitor pricing and adjust your tier table before you print new business cards this month.",
        "Set up error monitoring with SMS alerts so you know when the side project breaks at the worst hour.",
        "Back up the SQLite database nightly with cron because last corruption taught you humility the hard way.",
        "Timebox scope to three tabs for the MVP even if the ideas list is longer than your patience tonight.",
    ],
    "meditation": [
        "Sit ten minutes focusing only on nostril breath without opening a guided app mid-session like last week.",
        "Pay the retreat deposit before the refundable window closes and add the deadline to your calendar boldly.",
        "Wash the meditation cushion cover because allergies make every session sneezy and that is not zen.",
        "Journal three sentences right after sitting: mood number, distraction theme, and one kindness toward yourself.",
        "Turn on airplane mode before bed meditation so notifications cannot hijack the first minute anymore.",
        "Try walking meditation for twenty laps in the backyard counting twenty steps per breath cycle tonight.",
        "Set the singing bowl on felt so it does not slide on hardwood when struck gently like the teacher said.",
        "Practice loving-kindness toward the difficult coworker without forcing fake forgiveness wording tonight.",
        "Book the mindfulness class if panic spikes returned after the stressful project launch like you predicted.",
        "Dim lights to forty percent and use only warm bulbs for evening practice cues your body recognizes slowly.",
    ],
    "sleep": [
        "Wake at the same time seven days including weekends for two weeks so your circadian rhythm stabilizes finally.",
        "Replace the pillow if neck pain wakes you twice this week and keep the trial return receipt just in case.",
        "Install blackout shades or temporary foil if streetlight beams hit your pillow at five forty-five again.",
        "Cut caffeine after one p.m. for two weeks and log sleep latency in your notes app without judging harshly.",
        "Write tomorrow's top three worries on paper and tuck the paper in a drawer ritual before lights out tonight.",
        "Book a sleep study referral if snoring plus daytime sleepiness scored high on the screening quiz honestly.",
        "Cool the bedroom toward sixty-five if you can and negotiate blanket weights if your partner disagrees warmly.",
        "Charge the phone in the kitchen and read a paper book under warm lamp only until eyelids feel heavy.",
        "Try magnesium after dinner for two weeks and note dreams or side effects without spiraling WebMD anxiety.",
        "Take a morning light walk within thirty minutes of waking to anchor melatonin better than coffee alone does.",
    ],
    "chores": [
        "Scrub the microwave with lemon steam before in-laws visit Saturday afternoon because splatters judge you.",
        "Vacuum under couch cushions and coin-purse the change before the vacuum eats another quarter forever.",
        "Mop the kitchen with the right dilution printed on the bottle because sticky floors returned too fast last time.",
        "Dust ceiling fan blades with the pillowcase trick so dust falls inside the case not on the bedspread.",
        "Organize the junk drawer with bins labeled tape and batteries so roommates stop asking where tape lives.",
        "Take dead batteries to recycling Saturday because the junk drawer is becoming a small honest fire hazard.",
        "Clean windows inside on a cloudy day so streaks show less while you are still learning the squeegee angle.",
        "Schedule bulk pickup for the broken chair before the HOA fine notice arrives in the mail again quietly.",
        "Wash the shower curtain liner with towels and bleach per label because mildew edge is grossing you out.",
        "Declutter the coat closet and donate two coats you have not worn for two winters running without nostalgia.",
    ],
    "planning": [
        "Block ninety minutes Sunday for weekly review covering calendar, inbox, meal plan, and goals without skipping.",
        "Write three MITs for Monday on a sticky on your monitor before you close the laptop tonight honestly.",
        "Move vague someday tasks into calendar slots or delete them ruthlessly because someday is not a day name.",
        "Color-code calendar categories so overload reads visually without opening every event like archaeology.",
        "Defend no-meeting Wednesday for four weeks when invites appear because boundaries need repetition to stick.",
        "Export OKR snapshot to PDF dated today before leadership quietly moves the goalposts again next quarter.",
        "Add ten-minute buffers between meetings for water, bathroom, and walking so afternoons feel less fried.",
        "Email a delegation ask with deadline and success criteria instead of a vague help please that confuses people.",
        "Review quarterly goals Friday at four recurring so you adjust before the quarter ends without surprise tears.",
        "Tape a one-page quarter theme inside your notebook cover for daily alignment nudges you actually see.",
    ],
    "photography": [
        "Charge every battery tonight and format one spare card before the sunrise shoot tomorrow without excuses.",
        "Clean the sensor only if dust spots show at f sixteen against sky test shots before you scratch anything.",
        "Scout the location Saturday afternoon for light notes before the client session Sunday morning early.",
        "Back up RAW files to two drives before deleting camera cards even if you are tired and want bed now.",
        "Update pricing PDF with travel radius fee and overtime rate after last gig undervalued your Saturday badly.",
        "Cull eight hundred shots down to one twenty keepers without keeping five near-identical smiles emotionally.",
        "Schedule print lab test strips before ordering the large framed piece for the gallery wall next month.",
        "Read drone permit rules for that park because fines are not worth a viral clip that costs you rent money.",
        "Pack rain covers for camera bags because forecast lied on the last three outdoor weddings you shot.",
        "Load model releases on the tablet and save signed PDFs immediately into the client folder like a pro.",
    ],
    "volunteering": [
        "Finish the background check upload for youth mentoring before Saturday orientation at nine a.m. sharp.",
        "Sign up for a four-hour food bank shift next month and add steel-toe shoe reminder to your calendar note.",
        "Email the coordinator your shirt size and dietary restriction before the bulk shirt order closes Friday.",
        "Carpool with a neighbor to beach cleanup so only one vehicle needs the parking pass registered online.",
        "Attend the training webinar for the new volunteer portal because everyone complains but nobody reads docs.",
        "Bring signed waiver paper copies because digital signature failed at check-in last season embarrassingly.",
        "Organize donation receipts in a folder for taxes if the nonprofit sent deductible acknowledgment letters already.",
        "Thank the organizer with one specific story about the kid you helped read aloud so it feels human not generic.",
        "Recruit one friend for the next shift because teams underfill when the weather forecast looks rainy and sad.",
        "Keep a donation box by the door so clutter leaves weekly instead of piling until spring cleaning panic.",
    ],
    "shopping": [
        "Return the Amazon shoes by Tuesday six p.m. at the Whole Foods locker before the window closes tight.",
        "Compare dishwasher models with Consumer Reports and price-match in store with a printed page tomorrow.",
        "Order a birthday gift with guaranteed Thursday delivery and wrap it Sunday while you watch one episode.",
        "Book curbside grocery Saturday at ten a.m. before the good slots disappear Friday night like always happens.",
        "Return ill-fitting jeans with the receipt before Sunday mall hours get weird and you procrastinate again.",
        "Skip extended warranty unless repair history says it beats self-insuring with real numbers on paper tonight.",
        "Clip digital coupons in the store app before checkout Sunday because cashiers cannot retroapply discounts.",
        "Photograph new electronics serial numbers for insurance before you toss the boxes into recycling guilt.",
        "Order a vacuum filter now because waiting until allergies spike always costs you a week of sneezing.",
        "Build the meal-plan shopping list and stick to perimeter aisles for health and budget in one calm trip.",
    ],
    "commute": [
        "Download offline podcasts tonight because the subway tunnel kills signal on your route every morning reliably.",
        "Buy the monthly transit pass Monday before the rumored price hike email lands in your inbox without mercy.",
        "Pack umbrella and spare socks in your desk drawer because sudden rain ruined your shoes twice already.",
        "Trial bike commute Wednesday after you test the route Sunday and pack lights, patch kit, and U-lock fully.",
        "Share a carpool rotation spreadsheet so the same person stops driving every day unfairly without discussion.",
        "Leave ten minutes earlier Tuesday when train delays stack so stress does not spike before nine a.m. meetings.",
        "Renew the parking permit sticker before the first-of-month ticket risk returns like last quarter's surprise.",
        "Fund the regional rail app account now so the gate QR works when your phone battery is almost dead again.",
        "Queue an audiobook chapter for Friday's drive home so traffic feels less like a personal attack on you.",
        "Stretch hip flexors at the office after sitting commute plus desk because low back pain returned quietly.",
    ],
    "journaling": [
        "Write three specific wins from today with details so future you remembers why the day mattered at all.",
        "Answer what you would do if fear were zero for one page without editing mid-stream like a draft sermon.",
        "Glue the concert ticket stub into the journal and caption why that lyric hit you hard on Tuesday night.",
        "Schedule Sunday morning cafe journaling with your phone in airplane mode for the whole hour without cheating.",
        "Rewrite worries then tear the page into tiny pieces as disposal ritual instead of pretend mental deleting only.",
        "Track mood one to ten nightly for two weeks so your therapist sees a pattern instead of vibes only again.",
        "Migrate scattered notes into one monthly journal file so search stops failing when emotions spike suddenly.",
        "Try a ten-minute voice journal walk after work rant then delete if it is too embarrassing to keep forever.",
        "Decorate the journal cover so it invites you on a messy desk instead of feeling like another obligation pile.",
        "Photograph finished journal volume spines before you archive the box in the closet with dust and denial.",
    ],
    "podcasts": [
        "Queue three episodes for Friday's long drive and download on Wi-Fi Thursday night before you forget entirely.",
        "Trim silence automatically in app settings because host pauses kill pacing at two times speed honestly.",
        "Note timestamp highlights during listening and export them to the research doc for essay citations later.",
        "Cancel premium trial before renewal if you only wanted one exclusive series binge weekend without guilt.",
        "Rate the show five stars with one constructive sentence because creators read reviews like oxygen sometimes.",
        "Share episode link with a friend at fourteen thirty-two where the joke lands perfectly for their humor.",
        "Export OPML of podcast feeds before the redesign deletes your curated list like last year's bad surprise.",
        "Set a forty-minute sleep timer for bedtime podcasts so cliffhangers do not steal sleep like Tuesday did.",
        "Read guest bios before interview episodes so references land with full context instead of vague nods.",
        "Back up subscriptions spreadsheet because twelve dollars monthly times twelve is real money every year.",
    ],
    "news": [
        "Read one long investigative piece end-to-end without tab switching and summarize five bullets afterward.",
        "Verify a viral claim on a primary source before resharing because embarrassment lasts longer than likes fade.",
        "Cap news at twenty minutes each morning only so doomscroll does not replace your lunch walk again.",
        "Subscribe to one local digital paper for a month to support city hall coverage you actually use weekly.",
        "Draft a two-hundred-word letter to the editor about bike lane safety with a constructive tone before sending.",
        "Mute breaking-news push alerts for celebrity gossip because your nervous system deserves quieter mornings.",
        "Print the weekend crossword for analog Sunday coffee ritual without screen glare ruining the vibe gently.",
        "Follow one beat reporter instead of algorithmic homepage roulette that spikes adrenaline without insight.",
        "Log out of comment sections for a week because blood pressure spikes are not worth winning strangers online.",
        "Donate to nonprofit journalism if you read more than ten free articles monthly and guilt finally motivates you.",
    ],
    "dating": [
        "Rewrite your dating profile first paragraph with specific hobbies instead of the vague love to travel cliché.",
        "Schedule first date Tuesday seven p.m. coffee not dinner so exits stay easy if the vibe feels off early.",
        "Text a safety friend your location pin and expected end time before a blind meetup like you promised yourself.",
        "Plan three outfit options Wednesday night so Thursday work panic does not ruin confidence before the date.",
        "Research venue stairs versus elevator accessibility because last location embarrassed you both quietly.",
        "Set an early boundary about texting frequency if anxious attachment spikes your stress more than it helps.",
        "Delete apps for one month if burnout swiping matches shallow conversations only and you need a reset.",
        "Write a private reflection after date two about compatibility signals versus chemistry confusion without judgment.",
        "Skip gifts on date one because pressure reads weird and save thoughtful for date three if it gets there.",
        "Book therapy if rejection spirals return because self-worth should not hinge on match counts every Sunday night.",
    ],
    "parenting": [
        "Pack healthy lunchboxes Sunday with ice packs so Monday morning stops feeling like a screaming documentary.",
        "Email the teacher about IEP follow-up before the next progress report locks comments without your input.",
        "Book pediatric dentist six months out because good slots vanish if you wait until a tooth actually hurts loudly.",
        "Share a summer camp carpool spreadsheet with three families and a backup driver column before June chaos.",
        "Sign a screen-time contract with your kid and co-parent with weekend exceptions written in plain language.",
        "Buy next-size shoes on sale now because growth spurts hit mid-season every single year without warning.",
        "Photograph artwork backlog and recycle originals after digital copies exist in two places you trust tonight.",
        "Book a babysitter trial two hours before the anniversary dinner reservation deposit becomes nonrefundable pain.",
        "Lock adult meds in a box because toddler climbing era arrived faster than babyproofing plans predicted honestly.",
        "Post a picture bedtime routine checklist so transitions stop feeling like nightly negotiations without end.",
    ],
    "household": [
        "Replace HVAC filters using the size photo on your phone and set quarterly reminders before dust returns visibly.",
        "Test GFCI outlets in kitchen and bathrooms with a tester from the hardware trip you keep postponing weekly.",
        "Schedule chimney sweep before first fireplace night because creosote buildup is not romantic in real life.",
        "Organize warranty folder with purchase dates and model numbers photographed in a phone album labeled home.",
        "Bleach the washer gasket monthly because mildew smell on towels returned and guests notice faster than you.",
        "Label the breaker panel map taped inside the door so emergencies stop meaning guesswork in the dark basement.",
        "Mount a kitchen fire extinguisher and read PASS instructions aloud with household tonight without eye rolls.",
        "Clean dryer vent hose because lint buildup is a real house fire risk and not just a dad myth anymore honestly.",
        "Refresh emergency kit batteries and replace expired water jugs before storm season ads scare you again.",
        "Book pest inspection if pantry droppings returned because hoping it is old is cheaper until it is not.",
    ],
    "errands": [
        "Return library books Monday before fines start and renew the audiobook you are halfway through already.",
        "Submit prescription refill online and pick it up Wednesday after work before the pharmacy closes at seven.",
        "Book DMV REAL ID appointment online and gather birth certificate copies before the slot vanishes tomorrow.",
        "Mail packages Tuesday lunch when post office lines are shorter statistically according to your own notes app.",
        "Buy curtain rod hardware before guests arrive Friday because naked windows feel wrong in photos forever.",
        "Notarize the visa letter Thursday with correct ID copies laminated so the desk does not reject you twice.",
        "Wash the car Saturday before the road trip because bug splatter bakes into paint if you ignore it again.",
        "Donate clothes Sunday drive-through bin and photograph receipt if taxes might care about small deductions later.",
        "Pick up dry cleaning before Thursday interview because wrinkled shirt last time hurt confidence more than skills.",
        "Copy three spare keys tonight and leave one with a neighbor in a sealed envelope labeled emergency only.",
    ],
    "appointments": [
        "Confirm dermatology Tuesday nine twenty suite change email so you do not show at the wrong building again.",
        "Arrive fifteen minutes early to fill new patient forms honestly including family history nobody remembers aloud.",
        "Write your question list on phone notes before the specialist visit so fear does not erase your memory live.",
        "Upload insurance card photos to the portal before the telehealth link expires at the appointment start time.",
        "Schedule fasting blood draw with eight hours water only and set two alarms the night before without snooze.",
        "Save parking garage receipt for HSA reimbursement and note visit code on the folder tab before you forget.",
        "Reschedule dentist if you are coughing because some offices cancel sick patients at the door without refunds.",
        "Bring a printed medication list because memory fails under bright exam room lights more than you admit yearly.",
        "Block calendar buffer after therapy so you do not cry-walk straight into a performance review by accident.",
        "Download visit summary PDF within three days while details are fresh enough to catch billing mistakes early.",
    ],
    "therapy": [
        "Write three session goals max on Thursday before three p.m. so time is not wasted rambling without direction.",
        "Journal Friday's trigger with emotions and body sensations instead of only replaying the story like a movie.",
        "Schedule sliding-scale intake if insurance changed and attach the denial PDF they asked for in the portal.",
        "Practice the breathing homework daily this week because your therapist assigned it like medicine not optional.",
        "Respect the between-session email boundary unless safety is at risk because trust needs consistency weekly.",
        "Update psychiatrist about new side effects since the dose change two weeks ago without stoic minimizing language.",
        "Plan tea and a walk after hard sessions instead of alcohol because hangovers help nobody's nervous system heal.",
        "Cancel forty-eight hours ahead if sick so policy avoids fees and offer two reschedule windows politely.",
        "Bring printed mood charts if app data is hard to read on a small phone screen under fluorescent office lights.",
        "Celebrate tiny wins like grocery without panic because progress counts even when it feels silly to say aloud.",
    ],
    "networking": [
        "Send a LinkedIn note mentioning shared lab class instead of generic I would like to connect spam nobody answers.",
        "Book coffee Thursday eight thirty near their office with two agenda bullets max so respect feels mutual.",
        "Update elevator pitch to thirty seconds with current role metrics instead of outdated student bio language.",
        "Follow up conference contacts within forty-eight hours referencing a specific booth joke that landed well.",
        "Order new business cards with a QR portfolio link because the box ran out mid-meetup awkwardly last quarter.",
        "Skim attendee list before the industry dinner and pick three people you genuinely want to meet with reasons.",
        "Email mentor thank-you quarterly even without an ask because relationships decay without maintenance like plants.",
        "Rehearse active listening mentally before networking events because introvert battery drains faster than you admit.",
        "Decline vague recruiter calls without a job description link because your calendar already feels too thin.",
        "Update CRM last-contact notes so you stop double-emailing the same person embarrassingly every few months.",
    ],
    "training": [
        "Finish the OSHA module quiz above ninety percent before site badge renewal Friday or security will nag you.",
        "Schedule CPR recertification next month because workplace compliance emails already nagged you twice politely.",
        "Export course completion PDFs into the HR folder before audit season surprises you with missing paperwork.",
        "Book flights for corporate training week and email finance about per diem policy before prices spike again.",
        "Run the lab safety quiz twice because last near-miss with acid bottle scared you more than you joked afterward.",
        "Divide notebook sections by module before intensive week so panic search stops mid-test like last year.",
        "Email instructor about accommodation letter before week one not midterm crisis scramble without dignity.",
        "Pack nut-free snacks compliant with classroom policy because hunger ruins focus faster than boring slides.",
        "Join study Discord cohort A only because mixing sections confused assignment versions and grades hurt feelings.",
        "Sleep eight hours before certification exam because recall drops measurably under six hours for most humans.",
    ],
    "grading": [
        "Finish rubric scores for section B essays before midnight portal lock when students refresh like hawks online.",
        "Record comment bank snippets tonight so tomorrow grading speeds up without sounding robotic copy paste cold.",
        "Schedule regrade office hours Wednesday after exams return so the line does not explode your inbox afterward.",
        "Export grades CSV backup before uploading to registrar because upload bugs happen every semester without fail.",
        "Blind second-read borderline A minus papers with a colleague agreement protocol so fairness feels documented.",
        "Scan plagiarism flags for essay six and schedule a student meeting Thursday morning before rumors spread wildly.",
        "Email the class grade distribution stats only without individual names because privacy still matters here.",
        "Archive the term folder with syllabus keys and lock answer keys drive permissions before summer interns arrive.",
        "Return graded stacks Monday before class starts so hallway ambush questions shrink to survivable levels.",
        "Take a walk outside after grading ends because the next pile will arrive anyway and you deserve air first.",
    ],
    "applications": [
        "Tailor resume bullets to posting keywords and save as CompanyName_role_v3.pdf before you attach anything blindly.",
        "Write a cover letter paragraph linking their mission line two to your volunteer flood project with real numbers.",
        "Submit before eleven fifty-nine p.m. Pacific not Eastern because timezone mistakes burned you once already.",
        "Schedule mock interview Friday with a friend who hires engineers and record audio for cringe review alone.",
        "Read interviewer LinkedIn and prepare one genuine question about their published article from last spring politely.",
        "Send thank-you emails within two hours with one specific moment reference from each conversation without fluff.",
        "Track applications in a spreadsheet with dates and follow-ups so you stop double-emailing the same recruiter.",
        "Save job description PDF the day you apply because postings vanish before second rounds more than you think.",
        "Negotiate base salary before signing bonus because recurring comp compounds lifetime earnings more than lump sums.",
        "Request five business days on exploding offers politely when other final rounds are still legitimately moving.",
    ],
}

# sanity: every key once
keys_order = [
    "work", "life", "health", "home", "family", "learning", "fun", "growth", "money", "creativity",
    "community", "well-being", "sports", "travel", "entertainment", "fitness", "career", "friends",
    "rest", "food", "music", "reading", "art", "nature", "projects", "hobbies", "social", "spirituality",
    "movies", "comedy", "shows", "exercise", "study", "school", "research", "deadlines", "homework",
    "meetings", "email", "coding", "writing", "gaming", "cooking", "pets", "garden", "budget",
    "side projects", "meditation", "sleep", "chores", "planning", "photography", "volunteering",
    "shopping", "commute", "journaling", "podcasts", "news", "dating", "parenting", "household",
    "errands", "appointments", "therapy", "networking", "training", "grading", "applications",
]

lines = ["const WIZ_DEFAULT_COMMON_TASKS=" + js_arr(DEFAULT) + ";", "const WIZ_COMMON_TASKS_BY_CATEGORY={"]
for k in keys_order:
    key = "'well-being'" if k == "well-being" else ("'side projects'" if k == "side projects" else repr(k))
    lines.append(f"  {key}:{js_arr(CATS[k])},")
lines[-1] = lines[-1].rstrip(",")
lines.append("};")
new_block = "\n".join(lines) + "\n"

path.write_text(s[:start] + new_block + s[end:], encoding="utf-8")
print("wrote", len(new_block), "chars")
